spring:
  config:
    import:
      - classpath:config/application-attachment.yaml
      - classpath:config/application-autoconfigure.yaml
      - classpath:config/application-datasource.yaml
      - classpath:config/application-jackson.yaml
      - classpath:config/application-logging.yaml
      - classpath:config/application-messages.yaml
      - classpath:config/application-mp.yaml
      - classpath:config/application-pagehelper.yaml
      - classpath:config/application-redis.yaml
      - classpath:config/application-referer.yaml
      - classpath:config/application-ruoyi.yaml
      - classpath:config/application-server.yaml
      - classpath:config/application-servlet.yaml
      - classpath:config/application-token.yaml
      - classpath:config/application-user.yaml
      - classpath:config/application-xss.yaml
